CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    email varchar(255) NULL,
    created_at timestamp without time zone NULL
);

CREATE UNIQUE INDEX ux_users_username ON users (username);
